# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "thunderbolt" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-8e82e689-7842-4b3d-9206-95769df6bd38";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-8e82e689-7842-4b3d-9206-95769df6bd38".device = "/dev/disk/by-uuid/8e82e689-7842-4b3d-9206-95769df6bd38";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F335-564F";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home/kirin" =
    { device = "/dev/mapper/homecrypt";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."homecrypt".device = "/dev/disk/by-uuid/f59fc5cb-f4d9-4aa5-95a4-13a3982e4b19";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
